//! Project entity, boundary-shaped validation, and pure prefill defaults.
//!
//! Validation here is pure data checking (strings, path shapes). Checking
//! *reality* — the path exists, it is a git clone — belongs to the
//! imperative shell (`modules::registry::detect`), which validates at the
//! seam before events ever reach [`crate::modules::core::state::apply`].

use std::path::{Component, Path};

use serde::{Deserialize, Serialize};

use super::state::CoreError;

/// Default branch template offered when a Project is added. `{slug}` is
/// replaced with the Brief's slug when a Workspace is cut (task #5);
/// `{slot}` is reserved for the per-Project Slot integer.
pub const DEFAULT_BRANCH_TEMPLATE: &str = "helm/{slug}";

/// A repo the user has added, with a default base branch. All settings live
/// in Helmsmen's own registry — never in a file inside the repo, so a repo
/// can never configure its own trust.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    /// Stable registry id (generated by the shell, opaque to the core).
    pub id: String,
    /// Display name; defaults to the repo directory name.
    pub name: String,
    /// Canonical absolute path of the main checkout (git toplevel).
    pub repo_root: String,
    /// Branch Workspaces are cut off (detected, editable).
    pub base_branch: String,
    /// Absolute directory new worktrees are created under (prefilled,
    /// editable).
    pub worktree_home: String,
    /// Branch-name template for cut Workspaces (prefilled, editable).
    pub branch_template: String,
}

/// Prefill values computed for the add-Project form. Pure: derived only
/// from the canonical repo root and the user's home directory — no repo
/// file is ever read for configuration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectPrefill {
    pub name: String,
    pub worktree_home: String,
    pub branch_template: String,
}

/// Derive a Project name from the repo root's last path component.
pub fn repo_name(repo_root: &str) -> Option<String> {
    Path::new(repo_root)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .filter(|s| !s.trim().is_empty())
}

/// Compute the editable prefill for the add-Project form.
pub fn prefill(repo_root: &str, home_dir: &str) -> Result<ProjectPrefill, CoreError> {
    let name = repo_name(repo_root).ok_or(CoreError::Invalid {
        field: "repoRoot",
        reason: format!("cannot derive a project name from {repo_root:?}"),
    })?;
    let worktree_home = Path::new(home_dir)
        .join(".helmsmen")
        .join("worktrees")
        .join(&name)
        .to_string_lossy()
        .into_owned();
    Ok(ProjectPrefill {
        name,
        worktree_home,
        branch_template: DEFAULT_BRANCH_TEMPLATE.to_string(),
    })
}

/// Validate a Project's fields as pure data. Called by `apply` so no
/// invalid entity can ever enter the state.
pub fn validate_project(project: &Project) -> Result<(), CoreError> {
    if project.id.trim().is_empty() {
        return Err(CoreError::Invalid {
            field: "id",
            reason: "must not be empty".to_string(),
        });
    }
    if project.name.trim().is_empty() {
        return Err(CoreError::Invalid {
            field: "name",
            reason: "must not be empty".to_string(),
        });
    }
    validate_abs_path("repoRoot", &project.repo_root)?;
    validate_abs_path("worktreeHome", &project.worktree_home)?;
    validate_ref_name("baseBranch", &project.base_branch)?;
    validate_branch_template("branchTemplate", &project.branch_template)?;
    Ok(())
}

/// Reasonable subset of `git check-ref-format` for a single ref name,
/// implemented as pure string checks.
pub fn validate_ref_name(field: &'static str, name: &str) -> Result<(), CoreError> {
    let invalid = |reason: String| CoreError::Invalid { field, reason };
    if name.is_empty() {
        return Err(invalid("must not be empty".to_string()));
    }
    if name.len() > 255 {
        return Err(invalid("is too long".to_string()));
    }
    if name.starts_with('-') {
        return Err(invalid("must not start with '-'".to_string()));
    }
    if name == "@" || name.contains("@{") || name.contains("..") {
        return Err(invalid(format!("{name:?} is not a valid git ref name")));
    }
    if name.ends_with('.') {
        return Err(invalid("must not end with '.'".to_string()));
    }
    if let Some(bad) = name
        .chars()
        .find(|c| c.is_control() || " ~^:?*[\\".contains(*c))
    {
        return Err(invalid(format!("contains forbidden character {bad:?}")));
    }
    for component in name.split('/') {
        if component.is_empty() {
            return Err(invalid(
                "must not contain empty path components (leading, trailing, or double '/')"
                    .to_string(),
            ));
        }
        if component.starts_with('.') {
            return Err(invalid("no path component may start with '.'".to_string()));
        }
        if component.ends_with(".lock") {
            return Err(invalid(
                "no path component may end with '.lock'".to_string(),
            ));
        }
    }
    Ok(())
}

/// A branch template must produce a valid ref name once its placeholders
/// (`{slug}`, `{slot}`) are substituted; unknown placeholders are rejected.
pub fn validate_branch_template(field: &'static str, template: &str) -> Result<(), CoreError> {
    let expanded = template.replace("{slug}", "slug").replace("{slot}", "0");
    if expanded.contains('{') || expanded.contains('}') {
        return Err(CoreError::Invalid {
            field,
            reason: format!(
                "{template:?} contains an unknown placeholder (supported: {{slug}}, {{slot}})"
            ),
        });
    }
    validate_ref_name(field, &expanded)
}

/// An absolute path stored in the registry: non-empty, absolute, no `..`
/// components, no NUL (boundary validation as data — the shell also
/// canonicalizes against the real filesystem).
pub fn validate_abs_path(field: &'static str, path: &str) -> Result<(), CoreError> {
    let invalid = |reason: &str| CoreError::Invalid {
        field,
        reason: reason.to_string(),
    };
    if path.trim().is_empty() {
        return Err(invalid("must not be empty"));
    }
    if path.contains('\0') {
        return Err(invalid("must not contain a NUL byte"));
    }
    let parsed = Path::new(path);
    // `has_root()` rather than `is_absolute()`: identical on Unix, and on
    // Windows it keeps this a pure *shape* check (the shell canonicalizes
    // against the real filesystem before anything reaches the core).
    if !parsed.has_root() {
        return Err(invalid("must be an absolute path"));
    }
    if parsed
        .components()
        .any(|c| matches!(c, Component::ParentDir))
    {
        return Err(invalid("must not contain '..' components"));
    }
    Ok(())
}
