//! Workspace entity, Slot allocation, branch-template expansion, and the
//! `HELMSMEN_*` env set — all pure (task #5).
//!
//! A Workspace is one task: one git worktree on its own branch under a
//! Project. Everything here is data in -> data out; the git mechanics live
//! in `modules::registry::worktree` (imperative shell).

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::project::{validate_abs_path, validate_ref_name, Project};
use super::state::CoreError;

/// The first Slot ever handed out in a Project. Slots start at 1 so a
/// repo's derived values (`PORT=$((3000+HELMSMEN_SLOT))`, `DB=dev_$SLOT`)
/// never collide with the plain defaults the developer's own main-checkout
/// processes are already using.
pub const FIRST_SLOT: u32 = 1;

/// One task: one git worktree on its own branch under a Project. Live in
/// the registry until landed or scuttled; removal frees its Slot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Workspace {
    /// Stable registry id (generated by the shell, opaque to the core).
    pub id: String,
    /// The owning Project's registry id.
    pub project_id: String,
    /// Short name the Workspace was cut from (fills `{slug}` in the branch
    /// template and names the worktree directory).
    pub slug: String,
    /// Branch the worktree was cut on (branch template, expanded).
    pub branch: String,
    /// Canonical absolute path of the worktree.
    pub worktree_path: String,
    /// Lowest free integer among the Project's live Workspaces at cut
    /// time. Helmsmen hands it out and never interprets it.
    pub slot: u32,
}

/// Validate a slug as pure data: it must be safe both as a branch-template
/// substitution and as a worktree directory name (no separators, no
/// traversal, no git-ref metacharacters).
pub fn validate_slug(field: &'static str, slug: &str) -> Result<(), CoreError> {
    let invalid = |reason: String| CoreError::Invalid { field, reason };
    if slug.is_empty() {
        return Err(invalid("must not be empty".to_string()));
    }
    if slug.len() > 100 {
        return Err(invalid("is too long (max 100 characters)".to_string()));
    }
    if !slug
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
    {
        return Err(invalid(
            "may only contain ASCII letters, digits, '-', '_' and '.'".to_string(),
        ));
    }
    let first = slug.chars().next().expect("checked non-empty");
    let last = slug.chars().last().expect("checked non-empty");
    if !first.is_ascii_alphanumeric() || !last.is_ascii_alphanumeric() {
        return Err(invalid(
            "must start and end with a letter or digit".to_string(),
        ));
    }
    if slug.contains("..") {
        return Err(invalid("must not contain '..'".to_string()));
    }
    Ok(())
}

/// Expand a Project's branch template for one cut. The template was
/// validated at Project-add (`validate_branch_template`); the caller
/// validates the expansion again as a ref name before trusting it.
pub fn expand_branch_template(template: &str, slug: &str, slot: u32) -> String {
    template
        .replace("{slug}", slug)
        .replace("{slot}", &slot.to_string())
}

/// Directory name for a cut worktree. Includes the Slot so parallel cuts
/// of the same slug (branch template with `{slot}`) never collide on disk.
pub fn worktree_dir_name(slug: &str, slot: u32) -> String {
    format!("{slug}-{slot}")
}

/// Absolute worktree path for a cut, as data (the shell canonicalizes the
/// real directory after `git worktree add`).
pub fn worktree_path(worktree_home: &str, slug: &str, slot: u32) -> String {
    Path::new(worktree_home)
        .join(worktree_dir_name(slug, slot))
        .to_string_lossy()
        .into_owned()
}

/// The Slot for the next cut: the lowest integer >= [`FIRST_SLOT`] not
/// used by any of the Project's live Workspaces.
pub fn lowest_free_slot(workspaces: &[Workspace], project_id: &str) -> u32 {
    let mut taken: Vec<u32> = workspaces
        .iter()
        .filter(|w| w.project_id == project_id)
        .map(|w| w.slot)
        .collect();
    taken.sort_unstable();
    let mut candidate = FIRST_SLOT;
    for slot in taken {
        if slot == candidate {
            candidate += 1;
        } else if slot > candidate {
            break;
        }
    }
    candidate
}

/// The `HELMSMEN_*` env set: slot, workspace path, project, main checkout.
/// Everything spawned in the Workspace later (setup script, Processes,
/// Agent Sessions) receives exactly this set.
pub fn helmsmen_env(project: &Project, workspace: &Workspace) -> BTreeMap<String, String> {
    BTreeMap::from([
        ("HELMSMEN_SLOT".to_string(), workspace.slot.to_string()),
        (
            "HELMSMEN_WORKSPACE".to_string(),
            workspace.worktree_path.clone(),
        ),
        ("HELMSMEN_PROJECT".to_string(), project.name.clone()),
        (
            "HELMSMEN_MAIN_CHECKOUT".to_string(),
            project.repo_root.clone(),
        ),
    ])
}

/// Validate a Workspace's fields as pure data. Called by `apply` so no
/// invalid entity can ever enter the state; cross-entity rules (project
/// exists, Slot is the lowest free, uniqueness) live in the transition.
pub fn validate_workspace(workspace: &Workspace) -> Result<(), CoreError> {
    if workspace.id.trim().is_empty() {
        return Err(CoreError::Invalid {
            field: "id",
            reason: "must not be empty".to_string(),
        });
    }
    if workspace.project_id.trim().is_empty() {
        return Err(CoreError::Invalid {
            field: "projectId",
            reason: "must not be empty".to_string(),
        });
    }
    validate_slug("slug", &workspace.slug)?;
    validate_ref_name("branch", &workspace.branch)?;
    validate_abs_path("worktreePath", &workspace.worktree_path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> Project {
        Project {
            id: "prj-1".to_string(),
            name: "helmsmen".to_string(),
            repo_root: "/home/dev/src/helmsmen".to_string(),
            base_branch: "main".to_string(),
            worktree_home: "/home/dev/.helmsmen/worktrees/helmsmen".to_string(),
            branch_template: "helm/{slug}".to_string(),
        }
    }

    fn workspace(id: &str, project_id: &str, slot: u32) -> Workspace {
        Workspace {
            id: id.to_string(),
            project_id: project_id.to_string(),
            slug: format!("task-{slot}"),
            branch: format!("helm/task-{slot}"),
            worktree_path: format!("/home/dev/.helmsmen/worktrees/helmsmen/task-{slot}-{slot}"),
            slot,
        }
    }

    // --- slug validation ---

    #[test]
    fn reasonable_slugs_are_accepted() {
        for good in ["fix-login", "a", "V2", "db_seed", "release-1.2"] {
            validate_slug("slug", good)
                .unwrap_or_else(|e| panic!("expected {good:?} to be accepted, got {e}"));
        }
    }

    #[test]
    fn hostile_slugs_are_rejected() {
        for bad in [
            "",
            "has space",
            "a/b",
            "..",
            "a..b",
            "-leading-dash",
            ".leading-dot",
            "trailing-dash-",
            "trailing.",
            "back\\slash",
            "nul\0byte",
            "semi;colon",
            "dollar$",
            "tick`",
            &"x".repeat(101),
        ] {
            assert!(
                validate_slug("slug", bad).is_err(),
                "expected {bad:?} to be rejected"
            );
        }
    }

    // --- branch template expansion ---

    #[test]
    fn expands_slug_and_slot_placeholders() {
        assert_eq!(
            expand_branch_template("helm/{slug}", "fix-login", 1),
            "helm/fix-login"
        );
        assert_eq!(
            expand_branch_template("helm/{slug}-{slot}", "fix-login", 3),
            "helm/fix-login-3"
        );
    }

    // --- worktree path derivation ---

    #[test]
    fn worktree_dir_includes_slug_and_slot() {
        assert_eq!(worktree_dir_name("fix-login", 2), "fix-login-2");
    }

    #[test]
    fn worktree_path_joins_home_and_dir() {
        assert_eq!(
            Path::new(&worktree_path("/home/dev/wt", "fix-login", 1)),
            Path::new("/home/dev/wt/fix-login-1")
        );
    }

    // --- slot allocation ---

    #[test]
    fn first_cut_in_a_project_gets_slot_one() {
        assert_eq!(lowest_free_slot(&[], "prj-1"), 1);
    }

    #[test]
    fn slots_are_the_lowest_free_integer() {
        let ws = [workspace("ws-a", "prj-1", 1), workspace("ws-b", "prj-1", 2)];
        assert_eq!(lowest_free_slot(&ws, "prj-1"), 3);
    }

    #[test]
    fn freed_slots_are_reused() {
        // Slot 1 was freed (workspace removed); 2 and 3 are still live.
        let ws = [workspace("ws-b", "prj-1", 2), workspace("ws-c", "prj-1", 3)];
        assert_eq!(lowest_free_slot(&ws, "prj-1"), 1);
    }

    #[test]
    fn gaps_are_filled_before_the_end() {
        let ws = [workspace("ws-a", "prj-1", 1), workspace("ws-c", "prj-1", 3)];
        assert_eq!(lowest_free_slot(&ws, "prj-1"), 2);
    }

    #[test]
    fn slots_are_per_project() {
        let ws = [workspace("ws-a", "prj-1", 1), workspace("ws-b", "prj-1", 2)];
        assert_eq!(lowest_free_slot(&ws, "prj-2"), 1);
    }

    // --- HELMSMEN_* env assembly ---

    #[test]
    fn env_carries_slot_workspace_project_and_main_checkout() {
        let p = project();
        let mut w = workspace("ws-a", "prj-1", 2);
        w.worktree_path = "/home/dev/wt/fix-login-2".to_string();
        let env = helmsmen_env(&p, &w);
        assert_eq!(
            env,
            BTreeMap::from([
                ("HELMSMEN_SLOT".to_string(), "2".to_string()),
                (
                    "HELMSMEN_WORKSPACE".to_string(),
                    "/home/dev/wt/fix-login-2".to_string()
                ),
                ("HELMSMEN_PROJECT".to_string(), "helmsmen".to_string()),
                (
                    "HELMSMEN_MAIN_CHECKOUT".to_string(),
                    "/home/dev/src/helmsmen".to_string()
                ),
            ])
        );
    }

    // --- workspace validation ---

    #[test]
    fn valid_workspace_passes() {
        assert!(validate_workspace(&workspace("ws-a", "prj-1", 1)).is_ok());
    }

    #[test]
    fn empty_ids_are_rejected() {
        let mut w = workspace("ws-a", "prj-1", 1);
        w.id = " ".to_string();
        assert!(matches!(
            validate_workspace(&w),
            Err(CoreError::Invalid { field: "id", .. })
        ));
        let mut w = workspace("ws-a", "prj-1", 1);
        w.project_id = "".to_string();
        assert!(matches!(
            validate_workspace(&w),
            Err(CoreError::Invalid {
                field: "projectId",
                ..
            })
        ));
    }

    #[test]
    fn hostile_branch_is_rejected() {
        let mut w = workspace("ws-a", "prj-1", 1);
        w.branch = "-option-injection".to_string();
        assert!(matches!(
            validate_workspace(&w),
            Err(CoreError::Invalid {
                field: "branch",
                ..
            })
        ));
    }

    #[test]
    fn traversal_in_worktree_path_is_rejected() {
        let mut w = workspace("ws-a", "prj-1", 1);
        w.worktree_path = "/home/dev/wt/../../../etc".to_string();
        assert!(matches!(
            validate_workspace(&w),
            Err(CoreError::Invalid {
                field: "worktreePath",
                ..
            })
        ));
    }

    #[test]
    fn relative_worktree_path_is_rejected() {
        let mut w = workspace("ws-a", "prj-1", 1);
        w.worktree_path = "wt/fix-login-1".to_string();
        assert!(matches!(
            validate_workspace(&w),
            Err(CoreError::Invalid {
                field: "worktreePath",
                ..
            })
        ));
    }
}
